### ISSUE TITLE
Develop branch behind master

### ISSUE THREAD

**Issue by dhimmel** [greenelab/continuous_analysis#10]
the [`develop`](https://github.com/greenelab/continuous_analysis/tree/develop) branch states:

> This branch is 16 commits behind master.

Is `develop` in use? Why is it behind `master`? Where should I submit pull requests?

**Comment by cgreene** [comment]
ping @brettbj

**Comment by brettbj** [comment]
Please submit pull requests to develop (it just needs to be synced for readme changes made directly in github's ui, that did not need to go through CI)

I'll sync today.

**Comment by brettbj** [comment]
Synced and updated the drone example to run with version 0.7 (develop will naturally be 1 commit behind master due to drone commit)
