### ISSUE TITLE
Multi-container continous analysis using Docker compose

### ISSUE THREAD

**Issue by dhimmel** [greenelab/continuous_analysis#5]
As @brettbj and I have discussed, I'm skeptical that complex computational environments should always be coerced into a single docker image. Instead you may have multiple images that extend different parent images. For example, I may require an extended Neo4j (database) image and an extended Python image. 

It looks like [Docker Compose](https://docs.docker.com/compose/overview/) is the solution:

> Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.

Discovered Compose through @awm33 who implemented it in one of our Project Cognoma repositories: https://github.com/cognoma/core-service/pull/34. Just wanted to post this as something to keep in mind going forward.

**Comment by brettbj** [comment]
This is fairly easy to do in Drone 0.7 - see https://github.com/greenelab/continuous_analysis/blob/master/.drone.yml

You just have to specify different images to different parts of the pipeline (unnecessary for this example)
