### ISSUE TITLE
Does Kallisto's proprietary license create Docker incompatibility?

### ISSUE THREAD

**Issue by dhimmel** [greenelab/continuous_analysis#6]
This repo builds a Docker image that includes Kallisto, which has a proprietary [license that states](https://github.com/pachterlab/kallisto/blob/a2318033f4fe09858860d7ca7b0ec4df34d17372/license.txt):

> Permission to use, copy, modify, and distribute this software and its documentation for educational and research not-for-profit purposes, without fee and without a signed licensing agreement, is hereby granted

There are two potential issues with Kallisto's license:

1. Is the distribution of the Docker image ([`brettbj/continuous_analysis_base`](https://hub.docker.com/r/brettbj/continuous_analysis_base/)) commercial? If so, Kallisto's license would be violated. However, I think this is unlikely as no one is profiting from distributing this image.

2. Does creating an image with Kallisto violate linux's [GPL licensing](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html). Since Kallisto's license discriminates against commercial use, it's not open source software. According to [GNU FAQs](https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem), the answer is nuanced:
    > However, in many cases you can distribute the GPL-covered software alongside your proprietary system. To do this validly, you must make sure that the free and non-free programs communicate at arms length, that they are not combined in a way that would make them effectively a single program.
    >
    > The difference between this and “incorporating” the GPL-covered software is partly a matter of substance and partly form. The substantive part is this: if the two programs are combined so that they become effectively two parts of one program, then you can't treat them as two separate programs. So the GPL has to cover the whole thing.
    >
    > If the two programs remain well separated, like the compiler and the kernel, or like an editor and a shell, then you can treat them as two separate programs—but you have to do it properly. The issue is simply one of form: how you describe what you are doing. Why do we care about this? Because we want to make sure the users clearly understand the free status of the GPL-covered software in the collection.

    So if the Docker image makes Kallisto inseparable from Linux, then there may be licensing incompatibility. I personally think that the Docker image may keep Linux and Kallisto as "two separate programs."

Of course, this is not legal advice and I'm not a lawyer. I'm opening this issue as a place for us to collect our thoughts on the issue. At this point, I'm not suggesting that you remove Kallisto.

For more information, here's a [discussion of licensing issues](https://youtu.be/7493AmJdCwM "Managing open source software in the Docker era") in the Docker era.

**Comment by brettbj** [comment]
@dhimmel somehow I didn't see a notification for this.

1. I am comfortable saying it is not commercial.
2. Is more complicated, I'll need to look into the way a Docker image is structured.

**Comment by dhimmel** [comment]
Kallisto [updated its license](https://liorpachter.wordpress.com/2017/08/03/i-was-wrong-part-2/) to BSD 2-Clause!
