### ISSUE TITLE
Use GitHub deploy keys rather than personal access tokens

### ISSUE THREAD

**Issue by dhimmel** [greenelab/continuous_analysis#7]
Currently, it looks like `$git_publish_key` is a GitHub [personal access token](https://github.com/blog/1509-personal-api-tokens). This gives the CI service full access to a user's account. For improved security, it would be ideal to limit the CI service's write access to the specific repository being continuously analyzed.

Deploy keys [offer this functionality](https://developer.github.com/guides/managing-deploy-keys/#deploy-keys):

> A deploy key is an SSH key that is stored on your server and grants access to a single GitHub repository. This key is attached directly to the repository instead of to a personal user account.

As an example, see https://github.com/dhimmel/thinklytics/commit/39e2ae0eb8a277dca05c8a8523b030c2c20d26af, where I switched from a personal access token to a deploy key.

**Comment by dhimmel** [comment]
As @gwaygenomics and I just saw, it also seems to be easy for `$git_publish_key` to leak into the CI log.

This means you would have to redact logs before sharing.

**Comment by brettbj** [comment]
Agree. It should be noted that github does deactivate any keys accidentally pushed to a repository but any other way of distributing could result in the key leaking into the log. 

I think Drone 0.5 offers the best solution, pushing back to github is a supported workflow. You can also mount local drives. I am working on updating the docs for this but a nice example can be seen at - https://github.com/COMBINE-lab/continuous_analysis_rnaseq

**Comment by dhimmel** [comment]
Cool, so `COMBINE-lab/continuous_analysis_rnaseq` looks like it [uses](https://github.com/COMBINE-lab/continuous_analysis_rnaseq/blob/a2329ef1edc68a4335b8432aa03cf03bc4df6e21/.drone.yml#L32-L36) the Drone `git-push` [plugin](https://github.com/drone-plugins/drone-git-push/blob/bd40948b60de9408a7cc4fb5fcc2c423cad90be1/DOCS.md) that uses SSH keys.

How does the `GIT_PUSH_SSH_KEY` get set? That wasn't entirely clear to me from the `COMBINE-lab/continuous_analysis_rnaseq` repo.

**Comment by dhimmel** [comment]
Are you going to update [`.travis.yml`](https://github.com/greenelab/continuous_analysis/blob/b3cb92940a5fa4f7e7cf059107330ab29e771301/.travis.yml#L43) to use deploy keys? I'd be happy to submit a PR.

**Comment by brettbj** [comment]
@dhimmel if you want to submit a PR that'd be great

@rob-p would be best to answer the COMBINE-lab example

**Comment by rob-p** [comment]
@dhimmel --- The variant of the pipeline I built uses Drone's `git_push` plugin to push the results.  Drone has a notion of "secrets".  There is a secret "store" that is managed by the [drone command line interface](http://readme.drone.io/usage/secret-guide/).  You simply add the `GIT_PUSH_SSH_KEY` to the store and then sign your `.drone.yml` file to propagate the key.  You can see an example [here](https://github.com/drone-plugins/drone-git-push/blob/master/DOCS.md).

**Comment by brettbj** [comment]
Closed because I think Rob answered the question, and it’s now almost 5 months old so just cleaning. If you want to make a pull request to demonstrate that’d be great but I was afraid it’d be too complicated for the average user (and github does a good job of reducing risk by inactivating any leaky keys)
